/* snapz.c generated by valac, the Vala compiler
 * generated from snapz.vala, do not modify */

/* Snapz -- simple screenshot app.*/
/* Copyright (c) 2010 Evan Martin.  All rights reserved.*/

#include <glib.h>
#include <glib-object.h>
#include <cairo.h>
#include <gdk-pixbuf/gdk-pixdata.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <json-glib/json-glib.h>
#include <glib/gstdio.h>
#include <libsoup/soup.h>


#define TYPE_SHOT_CANVAS (shot_canvas_get_type ())
#define SHOT_CANVAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SHOT_CANVAS, ShotCanvas))
#define SHOT_CANVAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SHOT_CANVAS, ShotCanvasClass))
#define IS_SHOT_CANVAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SHOT_CANVAS))
#define IS_SHOT_CANVAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SHOT_CANVAS))
#define SHOT_CANVAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SHOT_CANVAS, ShotCanvasClass))

typedef struct _ShotCanvas ShotCanvas;
typedef struct _ShotCanvasClass ShotCanvasClass;
typedef struct _ShotCanvasPrivate ShotCanvasPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gdk_cursor_unref0(var) ((var == NULL) ? NULL : (var = (gdk_cursor_unref (var), NULL)))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_SNAPZ_WIN (snapz_win_get_type ())
#define SNAPZ_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SNAPZ_WIN, SnapzWin))
#define SNAPZ_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SNAPZ_WIN, SnapzWinClass))
#define IS_SNAPZ_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SNAPZ_WIN))
#define IS_SNAPZ_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SNAPZ_WIN))
#define SNAPZ_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SNAPZ_WIN, SnapzWinClass))

typedef struct _SnapzWin SnapzWin;
typedef struct _SnapzWinClass SnapzWinClass;
typedef struct _SnapzWinPrivate SnapzWinPrivate;
typedef struct _Block1Data Block1Data;
typedef struct _Block2Data Block2Data;

struct _ShotCanvas {
	GtkAspectFrame parent_instance;
	ShotCanvasPrivate * priv;
};

struct _ShotCanvasClass {
	GtkAspectFrameClass parent_class;
};

struct _ShotCanvasPrivate {
	GdkPixbuf* pixbuf;
	GdkPixbuf* pixbuf_scaled;
	GtkDrawingArea* canvas;
	GdkPoint sel_start;
	GdkPoint sel_end;
};

typedef enum  {
	IMGUR_ERROR_FAIL
} ImgurError;
#define IMGUR_ERROR imgur_error_quark ()
struct _SnapzWin {
	GtkWindow parent_instance;
	SnapzWinPrivate * priv;
};

struct _SnapzWinClass {
	GtkWindowClass parent_class;
};

struct _SnapzWinPrivate {
	ShotCanvas* canvas;
	GtkButton** selection_buttons;
	gint selection_buttons_length1;
	gint _selection_buttons_size_;
};

struct _Block1Data {
	int _ref_count_;
	SnapzWin * self;
	GtkMessageDialog* dlg;
};

struct _Block2Data {
	int _ref_count_;
	SnapzWin * self;
	GtkMessageDialog* dlg;
};


static gpointer shot_canvas_parent_class = NULL;
static gpointer snapz_win_parent_class = NULL;

GdkPixbuf* pixbuf_from_surface (cairo_surface_t* surface);
gint clamp (gint x, gint min, gint max);
GType shot_canvas_get_type (void);
#define SHOT_CANVAS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SHOT_CANVAS, ShotCanvasPrivate))
enum  {
	SHOT_CANVAS_DUMMY_PROPERTY
};
static void _lambda0_ (ShotCanvas* self);
static void __lambda0__gtk_widget_realize (GtkWidget* _sender, gpointer self);
static void shot_canvas_canvas_to_image (ShotCanvas* self, GdkPoint* p, GdkPoint* result);
static void shot_canvas_clamp_point (ShotCanvas* self, GdkPoint* p);
static gboolean _lambda1_ (GdkEventButton* event, ShotCanvas* self);
static gboolean __lambda1__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean _lambda2_ (GdkEventMotion* event, ShotCanvas* self);
static gboolean __lambda2__gtk_widget_motion_notify_event (GtkWidget* _sender, GdkEventMotion* event, gpointer self);
static gboolean _lambda3_ (GdkEventButton* event, ShotCanvas* self);
static gboolean __lambda3__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean shot_canvas_draw (ShotCanvas* self, GdkEventExpose* expose);
static gboolean _shot_canvas_draw_gtk_widget_expose_event (GtkWidget* _sender, GdkEventExpose* event, gpointer self);
static void _lambda4_ (ShotCanvas* self);
static void __lambda4__shot_canvas_selection_changed (ShotCanvas* _sender, gpointer self);
ShotCanvas* shot_canvas_new (GdkPixbuf* pixbuf);
ShotCanvas* shot_canvas_construct (GType object_type, GdkPixbuf* pixbuf);
void shot_canvas_save (ShotCanvas* self, const char* filename, GError** error);
gboolean shot_canvas_has_selection (ShotCanvas* self);
void shot_canvas_crop (ShotCanvas* self);
static void shot_canvas_draw_mask (ShotCanvas* self, cairo_t* ctx, float alpha, gint width, gint height, float x1, float y1, float x2, float y2);
void shot_canvas_highlight (ShotCanvas* self);
static void shot_canvas_scale_point (ShotCanvas* self, GdkPoint* p, float mult, GdkPoint* result);
static void shot_canvas_image_to_canvas (ShotCanvas* self, GdkPoint* p, GdkPoint* result);
static void shot_canvas_rescale_if_necessary (ShotCanvas* self);
static void shot_canvas_finalize (GObject* obj);
void read_file (const char* path, guint8** content, int* content_length1);
GQuark imgur_error_quark (void);
char* imgur_parse_response (const char* response, GError** error);
GType snapz_win_get_type (void);
#define SNAPZ_WIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SNAPZ_WIN, SnapzWinPrivate))
enum  {
	SNAPZ_WIN_DUMMY_PROPERTY
};
static void _lambda5_ (SnapzWin* self);
static void __lambda5__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _lambda6_ (SnapzWin* self);
static void __lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _lambda7_ (SnapzWin* self);
static void __lambda7__shot_canvas_selection_changed (ShotCanvas* _sender, gpointer self);
static void snapz_win_imgur_upload (SnapzWin* self);
static void _snapz_win_imgur_upload_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void snapz_win_save (SnapzWin* self);
static void _snapz_win_save_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self);
SnapzWin* snapz_win_new (GdkPixbuf* shot);
SnapzWin* snapz_win_construct (GType object_type, GdkPixbuf* shot);
static void _lambda8_ (Block1Data* _data1_);
static void __lambda8__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (Block1Data* _data1_);
static void _lambda9_ (Block2Data* _data2_);
static void __lambda9__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (Block2Data* _data2_);
static void snapz_win_finalize (GObject* obj);
GdkPixbuf* screenshot (void);
gint _vala_main (char** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static int _vala_strcmp0 (const char * str1, const char * str2);



#line 9 "snapz.vala"
GdkPixbuf* pixbuf_from_surface (cairo_surface_t* surface) {
#line 181 "snapz.c"
	GdkPixbuf* result = NULL;
	guchar* rgb32;
	gint width;
	gint height;
	gint stride;
	guchar* rgb24;
	guchar* dst;
#line 9 "snapz.vala"
	g_return_val_if_fail (surface != NULL, NULL);
#line 13 "snapz.vala"
	rgb32 = cairo_image_surface_get_data (surface);
#line 14 "snapz.vala"
	width = cairo_image_surface_get_width (surface);
#line 15 "snapz.vala"
	height = cairo_image_surface_get_height (surface);
#line 16 "snapz.vala"
	stride = cairo_image_surface_get_stride (surface);
#line 17 "snapz.vala"
	rgb24 = g_malloc ((gsize) ((width * height) * 3));
#line 18 "snapz.vala"
	dst = rgb24;
#line 203 "snapz.c"
	{
		gint y;
#line 19 "snapz.vala"
		y = 0;
#line 208 "snapz.c"
		{
			gboolean _tmp0_;
#line 19 "snapz.vala"
			_tmp0_ = TRUE;
#line 19 "snapz.vala"
			while (TRUE) {
#line 215 "snapz.c"
				guint32* src;
#line 19 "snapz.vala"
				if (!_tmp0_) {
#line 19 "snapz.vala"
					y = y + 1;
#line 221 "snapz.c"
				}
#line 19 "snapz.vala"
				_tmp0_ = FALSE;
#line 19 "snapz.vala"
				if (!(y < height)) {
#line 19 "snapz.vala"
					break;
#line 229 "snapz.c"
				}
#line 20 "snapz.vala"
				src = (guint32*) (rgb32 + (y * stride));
#line 233 "snapz.c"
				{
					gint x;
#line 21 "snapz.vala"
					x = 0;
#line 238 "snapz.c"
					{
						gboolean _tmp1_;
#line 21 "snapz.vala"
						_tmp1_ = TRUE;
#line 21 "snapz.vala"
						while (TRUE) {
#line 21 "snapz.vala"
							if (!_tmp1_) {
#line 21 "snapz.vala"
								x = x + 1;
#line 249 "snapz.c"
							}
#line 21 "snapz.vala"
							_tmp1_ = FALSE;
#line 21 "snapz.vala"
							if (!(x < width)) {
#line 21 "snapz.vala"
								break;
#line 257 "snapz.c"
							}
#line 22 "snapz.vala"
							*(dst++) = (guchar) (src[x] >> 16);
#line 23 "snapz.vala"
							*(dst++) = (guchar) (src[x] >> 8);
#line 24 "snapz.vala"
							*(dst++) = (guchar) src[x];
#line 265 "snapz.c"
						}
					}
				}
			}
		}
	}
	result = gdk_pixbuf_new_from_data ((guchar*) rgb24, GDK_COLORSPACE_RGB, FALSE, 8, width, height, width * 3, (GdkPixbufDestroyNotify) g_free, NULL);
#line 28 "snapz.vala"
	return result;
#line 275 "snapz.c"
}


#line 34 "snapz.vala"
gint clamp (gint x, gint min, gint max) {
#line 281 "snapz.c"
	gint result = 0;
#line 35 "snapz.vala"
	if (x < min) {
#line 285 "snapz.c"
		result = min;
#line 36 "snapz.vala"
		return result;
#line 289 "snapz.c"
	}
#line 37 "snapz.vala"
	if (x >= max) {
#line 293 "snapz.c"
		result = max - 1;
#line 38 "snapz.vala"
		return result;
#line 297 "snapz.c"
	}
	result = x;
#line 39 "snapz.vala"
	return result;
#line 302 "snapz.c"
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 60 "snapz.vala"
static void _lambda0_ (ShotCanvas* self) {
#line 313 "snapz.c"
	GdkCursor* _tmp0_;
#line 61 "snapz.vala"
	gdk_window_set_cursor (((GtkWidget*) self->priv->canvas)->window, _tmp0_ = gdk_cursor_new (GDK_CROSSHAIR));
#line 317 "snapz.c"
	_gdk_cursor_unref0 (_tmp0_);
}


#line 60 "snapz.vala"
static void __lambda0__gtk_widget_realize (GtkWidget* _sender, gpointer self) {
#line 324 "snapz.c"
	_lambda0_ (self);
}


#line 65 "snapz.vala"
static gboolean _lambda1_ (GdkEventButton* event, ShotCanvas* self) {
#line 331 "snapz.c"
	gboolean result = FALSE;
	GdkPoint _tmp2_ = {0};
	GdkPoint _tmp1_;
	GdkPoint _tmp0_ = {0};
#line 66 "snapz.vala"
	self->priv->sel_start = (shot_canvas_canvas_to_image (self, (_tmp1_ = (memset (&_tmp0_, 0, sizeof (GdkPoint)), _tmp0_.x = (gint) (*event).x, _tmp0_.y = (gint) (*event).y, _tmp0_), &_tmp1_), &_tmp2_), _tmp2_);
#line 69 "snapz.vala"
	shot_canvas_clamp_point (self, &self->priv->sel_start);
#line 70 "snapz.vala"
	self->priv->sel_end = self->priv->sel_start;
#line 71 "snapz.vala"
	g_signal_emit_by_name (self, "selection-changed");
#line 344 "snapz.c"
	result = TRUE;
#line 72 "snapz.vala"
	return result;
#line 348 "snapz.c"
}


#line 65 "snapz.vala"
static gboolean __lambda1__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
#line 354 "snapz.c"
	return _lambda1_ (event, self);
}


#line 74 "snapz.vala"
static gboolean _lambda2_ (GdkEventMotion* event, ShotCanvas* self) {
#line 361 "snapz.c"
	gboolean result = FALSE;
	GdkPoint _tmp2_ = {0};
	GdkPoint _tmp1_;
	GdkPoint _tmp0_ = {0};
#line 75 "snapz.vala"
	self->priv->sel_end = (shot_canvas_canvas_to_image (self, (_tmp1_ = (memset (&_tmp0_, 0, sizeof (GdkPoint)), _tmp0_.x = (gint) (*event).x, _tmp0_.y = (gint) (*event).y, _tmp0_), &_tmp1_), &_tmp2_), _tmp2_);
#line 78 "snapz.vala"
	shot_canvas_clamp_point (self, &self->priv->sel_end);
#line 79 "snapz.vala"
	g_signal_emit_by_name (self, "selection-changed");
#line 372 "snapz.c"
	result = TRUE;
#line 80 "snapz.vala"
	return result;
#line 376 "snapz.c"
}


#line 74 "snapz.vala"
static gboolean __lambda2__gtk_widget_motion_notify_event (GtkWidget* _sender, GdkEventMotion* event, gpointer self) {
#line 382 "snapz.c"
	return _lambda2_ (event, self);
}


#line 82 "snapz.vala"
static gboolean _lambda3_ (GdkEventButton* event, ShotCanvas* self) {
#line 389 "snapz.c"
	gboolean result = FALSE;
	GdkPoint _tmp2_ = {0};
	GdkPoint _tmp1_;
	GdkPoint _tmp0_ = {0};
	gboolean _tmp3_ = FALSE;
#line 83 "snapz.vala"
	self->priv->sel_end = (shot_canvas_canvas_to_image (self, (_tmp1_ = (memset (&_tmp0_, 0, sizeof (GdkPoint)), _tmp0_.x = (gint) (*event).x, _tmp0_.y = (gint) (*event).y, _tmp0_), &_tmp1_), &_tmp2_), _tmp2_);
#line 86 "snapz.vala"
	shot_canvas_clamp_point (self, &self->priv->sel_end);
#line 87 "snapz.vala"
	if (self->priv->sel_end.x == self->priv->sel_start.x) {
#line 87 "snapz.vala"
		_tmp3_ = self->priv->sel_end.y == self->priv->sel_start.y;
#line 403 "snapz.c"
	} else {
#line 87 "snapz.vala"
		_tmp3_ = FALSE;
#line 407 "snapz.c"
	}
#line 87 "snapz.vala"
	if (_tmp3_) {
#line 88 "snapz.vala"
		self->priv->sel_start.x = -1;
#line 413 "snapz.c"
	} else {
#line 90 "snapz.vala"
		if (self->priv->sel_end.x < self->priv->sel_start.x) {
#line 417 "snapz.c"
			gint t;
#line 91 "snapz.vala"
			t = self->priv->sel_start.x;
#line 92 "snapz.vala"
			self->priv->sel_start.x = self->priv->sel_end.x;
#line 93 "snapz.vala"
			self->priv->sel_end.x = t;
#line 425 "snapz.c"
		}
#line 95 "snapz.vala"
		if (self->priv->sel_end.y < self->priv->sel_start.y) {
#line 429 "snapz.c"
			gint t;
#line 96 "snapz.vala"
			t = self->priv->sel_start.y;
#line 97 "snapz.vala"
			self->priv->sel_start.y = self->priv->sel_end.y;
#line 98 "snapz.vala"
			self->priv->sel_end.y = t;
#line 437 "snapz.c"
		}
	}
#line 101 "snapz.vala"
	g_signal_emit_by_name (self, "selection-changed");
#line 442 "snapz.c"
	result = TRUE;
#line 102 "snapz.vala"
	return result;
#line 446 "snapz.c"
}


#line 82 "snapz.vala"
static gboolean __lambda3__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
#line 452 "snapz.c"
	return _lambda3_ (event, self);
}


#line 211 "snapz.vala"
static gboolean _shot_canvas_draw_gtk_widget_expose_event (GtkWidget* _sender, GdkEventExpose* event, gpointer self) {
#line 459 "snapz.c"
	return shot_canvas_draw (self, event);
}


#line 106 "snapz.vala"
static void _lambda4_ (ShotCanvas* self) {
#line 106 "snapz.vala"
	gtk_widget_queue_draw ((GtkWidget*) self);
#line 468 "snapz.c"
}


#line 106 "snapz.vala"
static void __lambda4__shot_canvas_selection_changed (ShotCanvas* _sender, gpointer self) {
#line 474 "snapz.c"
	_lambda4_ (self);
}


#line 47 "snapz.vala"
ShotCanvas* shot_canvas_construct (GType object_type, GdkPixbuf* pixbuf) {
#line 481 "snapz.c"
	ShotCanvas * self;
	GdkPixbuf* _tmp0_;
	GdkPixbuf* _tmp1_;
	GtkDrawingArea* _tmp2_;
#line 47 "snapz.vala"
	g_return_val_if_fail (pixbuf != NULL, NULL);
#line 488 "snapz.c"
	self = g_object_newv (object_type, 0, NULL);
#line 48 "snapz.vala"
	g_object_set ((GtkAspectFrame*) self, "obey-child", FALSE, NULL);
#line 49 "snapz.vala"
	gtk_frame_set_shadow_type ((GtkFrame*) self, GTK_SHADOW_NONE);
#line 51 "snapz.vala"
	self->priv->pixbuf = (_tmp0_ = _g_object_ref0 (pixbuf), _g_object_unref0 (self->priv->pixbuf), _tmp0_);
#line 52 "snapz.vala"
	self->priv->pixbuf_scaled = (_tmp1_ = NULL, _g_object_unref0 (self->priv->pixbuf_scaled), _tmp1_);
#line 53 "snapz.vala"
	g_object_set ((GtkAspectFrame*) self, "ratio", gdk_pixbuf_get_width (pixbuf) / ((float) gdk_pixbuf_get_height (pixbuf)), NULL);
#line 54 "snapz.vala"
	self->priv->sel_start.x = -1;
#line 56 "snapz.vala"
	self->priv->canvas = (_tmp2_ = g_object_ref_sink ((GtkDrawingArea*) gtk_drawing_area_new ()), _g_object_unref0 (self->priv->canvas), _tmp2_);
#line 57 "snapz.vala"
	gtk_widget_add_events ((GtkWidget*) self->priv->canvas, (gint) ((GDK_BUTTON_PRESS_MASK | GDK_BUTTON1_MOTION_MASK) | GDK_BUTTON_RELEASE_MASK));
#line 60 "snapz.vala"
	g_signal_connect_object ((GtkWidget*) self->priv->canvas, "realize", (GCallback) __lambda0__gtk_widget_realize, self, 0);
#line 65 "snapz.vala"
	g_signal_connect_object ((GtkWidget*) self->priv->canvas, "button-press-event", (GCallback) __lambda1__gtk_widget_button_press_event, self, 0);
#line 74 "snapz.vala"
	g_signal_connect_object ((GtkWidget*) self->priv->canvas, "motion-notify-event", (GCallback) __lambda2__gtk_widget_motion_notify_event, self, 0);
#line 82 "snapz.vala"
	g_signal_connect_object ((GtkWidget*) self->priv->canvas, "button-release-event", (GCallback) __lambda3__gtk_widget_button_release_event, self, 0);
#line 105 "snapz.vala"
	g_signal_connect_object ((GtkWidget*) self->priv->canvas, "expose-event", (GCallback) _shot_canvas_draw_gtk_widget_expose_event, self, 0);
#line 106 "snapz.vala"
	g_signal_connect_object (self, "selection-changed", (GCallback) __lambda4__shot_canvas_selection_changed, self, 0);
#line 107 "snapz.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->canvas);
#line 520 "snapz.c"
	return self;
}


#line 47 "snapz.vala"
ShotCanvas* shot_canvas_new (GdkPixbuf* pixbuf) {
#line 47 "snapz.vala"
	return shot_canvas_construct (TYPE_SHOT_CANVAS, pixbuf);
#line 529 "snapz.c"
}


#line 111 "snapz.vala"
void shot_canvas_save (ShotCanvas* self, const char* filename, GError** error) {
#line 535 "snapz.c"
	GError * _inner_error_;
#line 111 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 111 "snapz.vala"
	g_return_if_fail (filename != NULL);
#line 541 "snapz.c"
	_inner_error_ = NULL;
#line 112 "snapz.vala"
	gdk_pixbuf_save (self->priv->pixbuf, filename, "png", &_inner_error_, NULL, NULL);
#line 545 "snapz.c"
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


#line 116 "snapz.vala"
gboolean shot_canvas_has_selection (ShotCanvas* self) {
#line 555 "snapz.c"
	gboolean result = FALSE;
#line 116 "snapz.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 559 "snapz.c"
	result = self->priv->sel_start.x != (-1);
#line 117 "snapz.vala"
	return result;
#line 563 "snapz.c"
}


#line 124 "snapz.vala"
void shot_canvas_crop (ShotCanvas* self) {
#line 569 "snapz.c"
	GdkPixbuf* _tmp0_;
	GdkPixbuf* _tmp1_;
#line 124 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 125 "snapz.vala"
	self->priv->pixbuf = (_tmp0_ = gdk_pixbuf_new_subpixbuf (self->priv->pixbuf, self->priv->sel_start.x, self->priv->sel_start.y, self->priv->sel_end.x - self->priv->sel_start.x, self->priv->sel_end.y - self->priv->sel_start.y), _g_object_unref0 (self->priv->pixbuf), _tmp0_);
#line 128 "snapz.vala"
	self->priv->pixbuf_scaled = (_tmp1_ = NULL, _g_object_unref0 (self->priv->pixbuf_scaled), _tmp1_);
#line 129 "snapz.vala"
	self->priv->sel_start.x = -1;
#line 130 "snapz.vala"
	g_signal_emit_by_name (self, "selection-changed");
#line 131 "snapz.vala"
	g_object_set ((GtkAspectFrame*) self, "ratio", gdk_pixbuf_get_width (self->priv->pixbuf) / ((float) gdk_pixbuf_get_height (self->priv->pixbuf)), NULL);
#line 584 "snapz.c"
}


#line 135 "snapz.vala"
void shot_canvas_highlight (ShotCanvas* self) {
#line 590 "snapz.c"
	gint width;
	gint height;
	cairo_surface_t* surface;
	cairo_t* ctx;
	GdkPixbuf* _tmp0_;
	GdkPixbuf* _tmp1_;
#line 135 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 136 "snapz.vala"
	width = gdk_pixbuf_get_width (self->priv->pixbuf);
#line 137 "snapz.vala"
	height = gdk_pixbuf_get_height (self->priv->pixbuf);
#line 139 "snapz.vala"
	surface = cairo_image_surface_create (CAIRO_FORMAT_RGB24, width, height);
#line 140 "snapz.vala"
	ctx = cairo_create (surface);
#line 141 "snapz.vala"
	gdk_cairo_set_source_pixbuf (ctx, self->priv->pixbuf, (double) 0, (double) 0);
#line 142 "snapz.vala"
	cairo_paint (ctx);
#line 144 "snapz.vala"
	shot_canvas_draw_mask (self, ctx, 0.2f, width, height, (float) self->priv->sel_start.x, (float) self->priv->sel_start.y, (float) self->priv->sel_end.x, (float) self->priv->sel_end.y);
#line 147 "snapz.vala"
	self->priv->pixbuf = (_tmp0_ = pixbuf_from_surface (surface), _g_object_unref0 (self->priv->pixbuf), _tmp0_);
#line 148 "snapz.vala"
	self->priv->pixbuf_scaled = (_tmp1_ = NULL, _g_object_unref0 (self->priv->pixbuf_scaled), _tmp1_);
#line 149 "snapz.vala"
	self->priv->sel_start.x = -1;
#line 150 "snapz.vala"
	g_signal_emit_by_name (self, "selection-changed");
#line 621 "snapz.c"
	_cairo_surface_destroy0 (surface);
	_cairo_destroy0 (ctx);
}


#line 154 "snapz.vala"
static void shot_canvas_clamp_point (ShotCanvas* self, GdkPoint* p) {
#line 154 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 155 "snapz.vala"
	(*p).x = clamp ((*p).x, 0, gdk_pixbuf_get_width (self->priv->pixbuf));
#line 156 "snapz.vala"
	(*p).y = clamp ((*p).y, 0, gdk_pixbuf_get_height (self->priv->pixbuf));
#line 635 "snapz.c"
}


#line 160 "snapz.vala"
static void shot_canvas_scale_point (ShotCanvas* self, GdkPoint* p, float mult, GdkPoint* result) {
#line 641 "snapz.c"
	GdkPoint _tmp0_ = {0};
#line 160 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 645 "snapz.c"
	*result = (memset (&_tmp0_, 0, sizeof (GdkPoint)), _tmp0_.x = (gint) round ((double) ((*p).x * mult)), _tmp0_.y = (gint) round ((double) ((*p).y * mult)), _tmp0_);
#line 161 "snapz.vala"
	return;
#line 649 "snapz.c"
}


#line 168 "snapz.vala"
static void shot_canvas_canvas_to_image (ShotCanvas* self, GdkPoint* p, GdkPoint* result) {
#line 655 "snapz.c"
	GdkPoint _tmp0_ = {0};
#line 168 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 659 "snapz.c"
	*result = (shot_canvas_scale_point (self, p, gdk_pixbuf_get_width (self->priv->pixbuf) / ((float) ((GtkWidget*) self->priv->canvas)->allocation.width), &_tmp0_), _tmp0_);
#line 169 "snapz.vala"
	return;
#line 663 "snapz.c"
}


#line 173 "snapz.vala"
static void shot_canvas_image_to_canvas (ShotCanvas* self, GdkPoint* p, GdkPoint* result) {
#line 669 "snapz.c"
	GdkPoint _tmp0_ = {0};
#line 173 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 673 "snapz.c"
	*result = (shot_canvas_scale_point (self, p, ((GtkWidget*) self->priv->canvas)->allocation.width / ((float) gdk_pixbuf_get_width (self->priv->pixbuf)), &_tmp0_), _tmp0_);
#line 174 "snapz.vala"
	return;
#line 677 "snapz.c"
}


#line 179 "snapz.vala"
static void shot_canvas_rescale_if_necessary (ShotCanvas* self) {
#line 683 "snapz.c"
	gint width;
	gint height;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GdkPixbuf* _tmp2_;
#line 179 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 180 "snapz.vala"
	width = ((GtkWidget*) self->priv->canvas)->allocation.width;
#line 181 "snapz.vala"
	height = ((GtkWidget*) self->priv->canvas)->allocation.height;
#line 183 "snapz.vala"
	if (self->priv->pixbuf_scaled != NULL) {
#line 184 "snapz.vala"
		_tmp1_ = gdk_pixbuf_get_width (self->priv->pixbuf_scaled) == width;
#line 699 "snapz.c"
	} else {
#line 183 "snapz.vala"
		_tmp1_ = FALSE;
#line 703 "snapz.c"
	}
#line 183 "snapz.vala"
	if (_tmp1_) {
#line 185 "snapz.vala"
		_tmp0_ = gdk_pixbuf_get_height (self->priv->pixbuf_scaled) == height;
#line 709 "snapz.c"
	} else {
#line 183 "snapz.vala"
		_tmp0_ = FALSE;
#line 713 "snapz.c"
	}
#line 183 "snapz.vala"
	if (_tmp0_) {
#line 186 "snapz.vala"
		return;
#line 719 "snapz.c"
	}
#line 189 "snapz.vala"
	self->priv->pixbuf_scaled = (_tmp2_ = gdk_pixbuf_scale_simple (self->priv->pixbuf, width, height, GDK_INTERP_TILES), _g_object_unref0 (self->priv->pixbuf_scaled), _tmp2_);
#line 723 "snapz.c"
}


#line 194 "snapz.vala"
static void shot_canvas_draw_mask (ShotCanvas* self, cairo_t* ctx, float alpha, gint width, gint height, float x1, float y1, float x2, float y2) {
#line 729 "snapz.c"
	cairo_surface_t* mask;
	cairo_t* mask_ctx;
#line 194 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 194 "snapz.vala"
	g_return_if_fail (ctx != NULL);
#line 197 "snapz.vala"
	mask = cairo_surface_create_similar (cairo_get_target (ctx), CAIRO_CONTENT_ALPHA, width, height);
#line 200 "snapz.vala"
	mask_ctx = cairo_create (mask);
#line 201 "snapz.vala"
	cairo_set_source_rgba (mask_ctx, (double) 0, (double) 0, (double) 0, (double) alpha);
#line 202 "snapz.vala"
	cairo_paint (mask_ctx);
#line 203 "snapz.vala"
	cairo_set_operator (mask_ctx, CAIRO_OPERATOR_CLEAR);
#line 204 "snapz.vala"
	cairo_rectangle (mask_ctx, (double) x1, (double) y1, (double) (x2 - x1), (double) (y2 - y1));
#line 205 "snapz.vala"
	cairo_fill (mask_ctx);
#line 206 "snapz.vala"
	cairo_set_source_surface (ctx, mask, (double) 0, (double) 0);
#line 207 "snapz.vala"
	cairo_paint (ctx);
#line 754 "snapz.c"
	_cairo_surface_destroy0 (mask);
	_cairo_destroy0 (mask_ctx);
}


#line 211 "snapz.vala"
static gboolean shot_canvas_draw (ShotCanvas* self, GdkEventExpose* expose) {
#line 762 "snapz.c"
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	cairo_t* ctx;
#line 211 "snapz.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 212 "snapz.vala"
	if (((GtkWidget*) self->priv->canvas)->allocation.width == 1) {
#line 212 "snapz.vala"
		_tmp0_ = TRUE;
#line 772 "snapz.c"
	} else {
#line 212 "snapz.vala"
		_tmp0_ = ((GtkWidget*) self->priv->canvas)->allocation.height == 1;
#line 776 "snapz.c"
	}
#line 212 "snapz.vala"
	if (_tmp0_) {
#line 780 "snapz.c"
		result = FALSE;
#line 215 "snapz.vala"
		return result;
#line 784 "snapz.c"
	}
#line 218 "snapz.vala"
	shot_canvas_rescale_if_necessary (self);
#line 220 "snapz.vala"
	ctx = gdk_cairo_create ((GdkDrawable*) ((GtkWidget*) self->priv->canvas)->window);
#line 222 "snapz.vala"
	gdk_cairo_set_source_pixbuf (ctx, self->priv->pixbuf_scaled, (double) 0, (double) 0);
#line 223 "snapz.vala"
	cairo_paint (ctx);
#line 225 "snapz.vala"
	if (shot_canvas_has_selection (self)) {
#line 796 "snapz.c"
		GdkPoint _tmp1_ = {0};
		GdkPoint start;
		GdkPoint _tmp2_ = {0};
		GdkPoint end;
		gint _tmp4__length1;
		double* _tmp4_;
		double* _tmp3_ = NULL;
#line 226 "snapz.vala"
		start = (shot_canvas_image_to_canvas (self, &self->priv->sel_start, &_tmp1_), _tmp1_);
#line 227 "snapz.vala"
		end = (shot_canvas_image_to_canvas (self, &self->priv->sel_end, &_tmp2_), _tmp2_);
#line 230 "snapz.vala"
		shot_canvas_draw_mask (self, ctx, 0.1f, ((GtkWidget*) self->priv->canvas)->allocation.width, ((GtkWidget*) self->priv->canvas)->allocation.height, (float) start.x, (float) start.y, (float) end.x, (float) end.y);
#line 235 "snapz.vala"
		cairo_translate (ctx, 0.5, 0.5);
#line 236 "snapz.vala"
		cairo_set_line_width (ctx, (double) 1);
#line 238 "snapz.vala"
		cairo_set_source_rgb (ctx, (double) 0, (double) 0, (double) 0);
#line 239 "snapz.vala"
		cairo_rectangle (ctx, (double) start.x, (double) start.y, (double) (end.x - start.x), (double) (end.y - start.y));
#line 241 "snapz.vala"
		cairo_stroke (ctx);
#line 243 "snapz.vala"
		cairo_set_source_rgb (ctx, (double) 1, (double) 1, (double) 1);
#line 244 "snapz.vala"
		cairo_set_dash (ctx, (_tmp4_ = (_tmp3_ = g_new0 (double, 2), _tmp3_[0] = (double) 5, _tmp3_[1] = (double) 5, _tmp3_), _tmp4__length1 = 2, _tmp4_), 2, (double) 0);
#line 824 "snapz.c"
		_tmp4_ = (g_free (_tmp4_), NULL);
#line 245 "snapz.vala"
		cairo_rectangle (ctx, (double) start.x, (double) start.y, (double) (end.x - start.x), (double) (end.y - start.y));
#line 247 "snapz.vala"
		cairo_stroke (ctx);
#line 830 "snapz.c"
	}
	result = TRUE;
	_cairo_destroy0 (ctx);
#line 250 "snapz.vala"
	return result;
#line 836 "snapz.c"
}


static void shot_canvas_class_init (ShotCanvasClass * klass) {
	shot_canvas_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ShotCanvasPrivate));
	G_OBJECT_CLASS (klass)->finalize = shot_canvas_finalize;
	g_signal_new ("selection_changed", TYPE_SHOT_CANVAS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void shot_canvas_instance_init (ShotCanvas * self) {
	self->priv = SHOT_CANVAS_GET_PRIVATE (self);
}


static void shot_canvas_finalize (GObject* obj) {
	ShotCanvas * self;
	self = SHOT_CANVAS (obj);
	_g_object_unref0 (self->priv->pixbuf);
	_g_object_unref0 (self->priv->pixbuf_scaled);
	_g_object_unref0 (self->priv->canvas);
	G_OBJECT_CLASS (shot_canvas_parent_class)->finalize (obj);
}


GType shot_canvas_get_type (void) {
	static volatile gsize shot_canvas_type_id__volatile = 0;
	if (g_once_init_enter (&shot_canvas_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ShotCanvasClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) shot_canvas_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ShotCanvas), 0, (GInstanceInitFunc) shot_canvas_instance_init, NULL };
		GType shot_canvas_type_id;
		shot_canvas_type_id = g_type_register_static (GTK_TYPE_ASPECT_FRAME, "ShotCanvas", &g_define_type_info, 0);
		g_once_init_leave (&shot_canvas_type_id__volatile, shot_canvas_type_id);
	}
	return shot_canvas_type_id__volatile;
}


#line 269 "snapz.vala"
void read_file (const char* path, guint8** content, int* content_length1) {
#line 877 "snapz.c"
	guint8* _tmp0_;
	gsize total_len;
	gsize len;
	FILE* file;
	gint _tmp3_;
#line 269 "snapz.vala"
	g_return_if_fail (path != NULL);
#line 885 "snapz.c"
	if (content != NULL) {
		*content = NULL;
	}
#line 270 "snapz.vala"
	*content = (_tmp0_ = g_new0 (guint8, 16 << 10), *content = (g_free (*content), NULL), *content_length1 = 16 << 10, _tmp0_);
#line 271 "snapz.vala"
	total_len = (gsize) 0;
#line 272 "snapz.vala"
	len = (gsize) 0;
#line 273 "snapz.vala"
	file = fopen (path, "rb");
#line 897 "snapz.c"
	{
		gboolean _tmp1_;
#line 274 "snapz.vala"
		_tmp1_ = TRUE;
#line 274 "snapz.vala"
		while (TRUE) {
#line 904 "snapz.c"
			guint8 buf[4096] = {0};
#line 274 "snapz.vala"
			if (!_tmp1_) {
#line 283 "snapz.vala"
				if (!(len > 0)) {
#line 283 "snapz.vala"
					break;
#line 912 "snapz.c"
				}
			}
#line 274 "snapz.vala"
			_tmp1_ = FALSE;
#line 276 "snapz.vala"
			len = fread (buf, 1, 4096, file);
#line 277 "snapz.vala"
			if (len > 0) {
#line 278 "snapz.vala"
				if ((total_len + len) > (*content_length1)) {
#line 923 "snapz.c"
					gint _tmp2_;
#line 279 "snapz.vala"
					_tmp2_ = (*content_length1) * 2;
#line 279 "snapz.vala"
					*content = g_renew (guint8, *content, (*content_length1) * 2);
#line 279 "snapz.vala"
					(_tmp2_ > (*content_length1)) ? memset ((*content) + (*content_length1), 0, sizeof (guint8) * (_tmp2_ - (*content_length1))) : NULL;
#line 279 "snapz.vala"
					*content_length1 = _tmp2_;
#line 933 "snapz.c"
				}
#line 280 "snapz.vala"
				memcpy (((guint8*) (*content)) + total_len, buf, len);
#line 281 "snapz.vala"
				total_len = total_len + len;
#line 939 "snapz.c"
			}
		}
	}
#line 284 "snapz.vala"
	_tmp3_ = (gint) total_len;
#line 284 "snapz.vala"
	*content = g_renew (guint8, *content, (gint) total_len);
#line 284 "snapz.vala"
	(_tmp3_ > (*content_length1)) ? memset ((*content) + (*content_length1), 0, sizeof (guint8) * (_tmp3_ - (*content_length1))) : NULL;
#line 284 "snapz.vala"
	*content_length1 = _tmp3_;
#line 951 "snapz.c"
	_fclose0 (file);
}


GQuark imgur_error_quark (void) {
	return g_quark_from_static_string ("imgur_error-quark");
}


static gpointer _json_object_ref0 (gpointer self) {
	return self ? json_object_ref (self) : NULL;
}


static gpointer _g_error_copy0 (gpointer self) {
	return self ? g_error_copy (self) : NULL;
}


#line 290 "snapz.vala"
char* imgur_parse_response (const char* response, GError** error) {
#line 973 "snapz.c"
	char* result = NULL;
	GError * _inner_error_;
	JsonParser* parser;
#line 290 "snapz.vala"
	g_return_val_if_fail (response != NULL, NULL);
#line 979 "snapz.c"
	_inner_error_ = NULL;
#line 291 "snapz.vala"
	parser = json_parser_new ();
#line 983 "snapz.c"
	{
		gboolean _tmp0_;
		JsonObject* root;
		JsonObject* rsp;
		char* stat;
#line 293 "snapz.vala"
		_tmp0_ = json_parser_load_from_data (parser, response, -1, &_inner_error_);
#line 991 "snapz.c"
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == IMGUR_ERROR) {
				goto __catch0_imgur_error;
			}
			goto __catch0_g_error;
		}
#line 293 "snapz.vala"
		if (!_tmp0_) {
#line 1000 "snapz.c"
			_inner_error_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, "Couldn't parse response");
			{
				if (_inner_error_->domain == IMGUR_ERROR) {
					goto __catch0_imgur_error;
				}
				goto __catch0_g_error;
			}
		}
#line 296 "snapz.vala"
		root = _json_object_ref0 (json_node_get_object (json_parser_get_root (parser)));
#line 297 "snapz.vala"
		if (!json_object_has_member (root, "rsp")) {
#line 1013 "snapz.c"
			_inner_error_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, "No 'rsp' element in response");
			{
				_json_object_unref0 (root);
				if (_inner_error_->domain == IMGUR_ERROR) {
					goto __catch0_imgur_error;
				}
				goto __catch0_g_error;
			}
		}
#line 299 "snapz.vala"
		rsp = _json_object_ref0 (json_object_get_object_member (root, "rsp"));
#line 301 "snapz.vala"
		if (!json_object_has_member (rsp, "stat")) {
#line 1027 "snapz.c"
			_inner_error_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, "No 'stat' element in response");
			{
				_json_object_unref0 (root);
				_json_object_unref0 (rsp);
				if (_inner_error_->domain == IMGUR_ERROR) {
					goto __catch0_imgur_error;
				}
				goto __catch0_g_error;
			}
		}
#line 303 "snapz.vala"
		stat = g_strdup (json_object_get_string_member (rsp, "stat"));
#line 305 "snapz.vala"
		if (_vala_strcmp0 (stat, "ok") == 0) {
#line 1042 "snapz.c"
			JsonObject* image;
			char* url;
#line 306 "snapz.vala"
			image = _json_object_ref0 (json_object_get_object_member (rsp, "image"));
#line 307 "snapz.vala"
			if (!json_object_has_member (rsp, "image")) {
#line 1049 "snapz.c"
				_inner_error_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, "No 'image' element in response");
				{
					_json_object_unref0 (image);
					_json_object_unref0 (root);
					_json_object_unref0 (rsp);
					_g_free0 (stat);
					if (_inner_error_->domain == IMGUR_ERROR) {
						goto __catch0_imgur_error;
					}
					goto __catch0_g_error;
				}
			}
#line 309 "snapz.vala"
			if (!json_object_has_member (image, "original_image")) {
#line 1064 "snapz.c"
				_inner_error_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, "No 'original_image' element in " "response");
				{
					_json_object_unref0 (image);
					_json_object_unref0 (root);
					_json_object_unref0 (rsp);
					_g_free0 (stat);
					if (_inner_error_->domain == IMGUR_ERROR) {
						goto __catch0_imgur_error;
					}
					goto __catch0_g_error;
				}
			}
#line 312 "snapz.vala"
			url = g_strdup (json_object_get_string_member (image, "original_image"));
#line 1079 "snapz.c"
			result = url;
			_json_object_unref0 (image);
			_json_object_unref0 (root);
			_json_object_unref0 (rsp);
			_g_free0 (stat);
			_g_object_unref0 (parser);
#line 313 "snapz.vala"
			return result;
#line 1088 "snapz.c"
		}
#line 316 "snapz.vala"
		if (!json_object_has_member (rsp, "error_msg")) {
#line 1092 "snapz.c"
			_inner_error_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, "No 'error_msg' in response");
			{
				_json_object_unref0 (root);
				_json_object_unref0 (rsp);
				_g_free0 (stat);
				if (_inner_error_->domain == IMGUR_ERROR) {
					goto __catch0_imgur_error;
				}
				goto __catch0_g_error;
			}
		}
		_inner_error_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, json_object_get_string_member (rsp, "error_msg"));
		{
			_json_object_unref0 (root);
			_json_object_unref0 (rsp);
			_g_free0 (stat);
			if (_inner_error_->domain == IMGUR_ERROR) {
				goto __catch0_imgur_error;
			}
			goto __catch0_g_error;
		}
		_json_object_unref0 (root);
		_json_object_unref0 (rsp);
		_g_free0 (stat);
	}
	goto __finally0;
	__catch0_imgur_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			_inner_error_ = _g_error_copy0 (e);
			{
				_g_error_free0 (e);
				_g_object_unref0 (parser);
				goto __finally0;
			}
			_g_error_free0 (e);
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			char* _tmp1_;
			GError* _tmp2_;
			_inner_error_ = (_tmp2_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, _tmp1_ = g_strconcat ("parser error: ", e->message, NULL)), _g_free0 (_tmp1_), _tmp2_);
			{
				_g_error_free0 (e);
				_g_object_unref0 (parser);
				goto __finally0;
			}
			_g_error_free0 (e);
		}
	}
	__finally0:
	{
		if (_inner_error_->domain == IMGUR_ERROR) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (parser);
			return NULL;
		} else {
			_g_object_unref0 (parser);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_g_object_unref0 (parser);
}


#line 342 "snapz.vala"
static void _lambda5_ (SnapzWin* self) {
#line 343 "snapz.vala"
	shot_canvas_crop (self->priv->canvas);
#line 1173 "snapz.c"
}


#line 342 "snapz.vala"
static void __lambda5__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 1179 "snapz.c"
	_lambda5_ (self);
}


#line 348 "snapz.vala"
static void _lambda6_ (SnapzWin* self) {
#line 349 "snapz.vala"
	shot_canvas_highlight (self->priv->canvas);
#line 1188 "snapz.c"
}


#line 348 "snapz.vala"
static void __lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 1194 "snapz.c"
	_lambda6_ (self);
}


#line 357 "snapz.vala"
static void _lambda7_ (SnapzWin* self) {
#line 1201 "snapz.c"
	{
		GtkButton** button_collection;
		int button_collection_length1;
		int button_it;
#line 358 "snapz.vala"
		button_collection = self->priv->selection_buttons;
#line 1208 "snapz.c"
		button_collection_length1 = self->priv->selection_buttons_length1;
		for (button_it = 0; button_it < self->priv->selection_buttons_length1; button_it = button_it + 1) {
			GtkButton* button;
			button = _g_object_ref0 (button_collection[button_it]);
			{
#line 359 "snapz.vala"
				gtk_widget_set_sensitive ((GtkWidget*) button, shot_canvas_has_selection (self->priv->canvas));
#line 1216 "snapz.c"
				_g_object_unref0 (button);
			}
		}
	}
}


#line 357 "snapz.vala"
static void __lambda7__shot_canvas_selection_changed (ShotCanvas* _sender, gpointer self) {
#line 1226 "snapz.c"
	_lambda7_ (self);
}


#line 398 "snapz.vala"
static void _snapz_win_imgur_upload_gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 1233 "snapz.c"
	snapz_win_imgur_upload (self);
}


#line 380 "snapz.vala"
static void _snapz_win_save_gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 1240 "snapz.c"
	snapz_win_save (self);
}


#line 7712 "gtk+-2.0.vapi"
static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self) {
#line 1247 "snapz.c"
	gtk_main_quit ();
}


#line 328 "snapz.vala"
SnapzWin* snapz_win_construct (GType object_type, GdkPixbuf* shot) {
#line 1254 "snapz.c"
	SnapzWin * self;
	GtkVBox* vbox;
	ShotCanvas* _tmp0_;
	GtkHButtonBox* bbox;
	GtkButton* crop_button;
	GtkButton* highlight_button;
	GtkButton** _tmp2_;
	GtkButton** _tmp1_ = NULL;
	GtkButton* imgur_button;
	GtkButton* save_button;
#line 328 "snapz.vala"
	g_return_val_if_fail (shot != NULL, NULL);
#line 1267 "snapz.c"
	self = g_object_newv (object_type, 0, NULL);
#line 329 "snapz.vala"
	gtk_window_set_title ((GtkWindow*) self, "Snapz");
#line 330 "snapz.vala"
	gtk_window_set_default_size ((GtkWindow*) self, gdk_pixbuf_get_width (shot) / 2, gdk_pixbuf_get_height (shot) / 2);
#line 332 "snapz.vala"
	vbox = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 12));
#line 333 "snapz.vala"
	gtk_container_set_border_width ((GtkContainer*) vbox, (guint) 12);
#line 335 "snapz.vala"
	self->priv->canvas = (_tmp0_ = g_object_ref_sink (shot_canvas_new (shot)), _g_object_unref0 (self->priv->canvas), _tmp0_);
#line 336 "snapz.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) self->priv->canvas, TRUE, TRUE, (guint) 0);
#line 338 "snapz.vala"
	bbox = g_object_ref_sink ((GtkHButtonBox*) gtk_hbutton_box_new ());
#line 339 "snapz.vala"
	g_object_set ((GtkButtonBox*) bbox, "layout-style", GTK_BUTTONBOX_START, NULL);
#line 341 "snapz.vala"
	crop_button = g_object_ref_sink ((GtkButton*) gtk_button_new_with_mnemonic ("_Crop"));
#line 342 "snapz.vala"
	g_signal_connect_object (crop_button, "clicked", (GCallback) __lambda5__gtk_button_clicked, self, 0);
#line 345 "snapz.vala"
	gtk_box_pack_start ((GtkBox*) bbox, (GtkWidget*) crop_button, FALSE, FALSE, (guint) 0);
#line 347 "snapz.vala"
	highlight_button = g_object_ref_sink ((GtkButton*) gtk_button_new_with_mnemonic ("_Highlight"));
#line 348 "snapz.vala"
	g_signal_connect_object (highlight_button, "clicked", (GCallback) __lambda6__gtk_button_clicked, self, 0);
#line 351 "snapz.vala"
	gtk_box_pack_start ((GtkBox*) bbox, (GtkWidget*) highlight_button, FALSE, FALSE, (guint) 0);
#line 353 "snapz.vala"
	self->priv->selection_buttons = (_tmp2_ = (_tmp1_ = g_new0 (GtkButton*, 2 + 1), _tmp1_[0] = _g_object_ref0 (crop_button), _tmp1_[1] = _g_object_ref0 (highlight_button), _tmp1_), self->priv->selection_buttons = (_vala_array_free (self->priv->selection_buttons, self->priv->selection_buttons_length1, (GDestroyNotify) g_object_unref), NULL), self->priv->selection_buttons_length1 = 2, self->priv->_selection_buttons_size_ = self->priv->selection_buttons_length1, _tmp2_);
#line 1299 "snapz.c"
	{
		GtkButton** button_collection;
		int button_collection_length1;
		int button_it;
#line 354 "snapz.vala"
		button_collection = self->priv->selection_buttons;
#line 1306 "snapz.c"
		button_collection_length1 = self->priv->selection_buttons_length1;
		for (button_it = 0; button_it < self->priv->selection_buttons_length1; button_it = button_it + 1) {
			GtkButton* button;
			button = _g_object_ref0 (button_collection[button_it]);
			{
#line 355 "snapz.vala"
				gtk_widget_set_sensitive ((GtkWidget*) button, FALSE);
#line 1314 "snapz.c"
				_g_object_unref0 (button);
			}
		}
	}
#line 357 "snapz.vala"
	g_signal_connect_object (self->priv->canvas, "selection-changed", (GCallback) __lambda7__shot_canvas_selection_changed, self, 0);
#line 362 "snapz.vala"
	imgur_button = g_object_ref_sink ((GtkButton*) gtk_button_new_with_mnemonic ("_imgur"));
#line 363 "snapz.vala"
	g_signal_connect_object (imgur_button, "clicked", (GCallback) _snapz_win_imgur_upload_gtk_button_clicked, self, 0);
#line 364 "snapz.vala"
	gtk_box_pack_end ((GtkBox*) bbox, (GtkWidget*) imgur_button, FALSE, FALSE, (guint) 0);
#line 365 "snapz.vala"
	gtk_button_box_set_child_secondary ((GtkButtonBox*) bbox, (GtkWidget*) imgur_button, TRUE);
#line 367 "snapz.vala"
	save_button = g_object_ref_sink ((GtkButton*) gtk_button_new_with_mnemonic ("_Save"));
#line 368 "snapz.vala"
	g_signal_connect_object (save_button, "clicked", (GCallback) _snapz_win_save_gtk_button_clicked, self, 0);
#line 369 "snapz.vala"
	gtk_box_pack_end ((GtkBox*) bbox, (GtkWidget*) save_button, FALSE, FALSE, (guint) 0);
#line 370 "snapz.vala"
	gtk_button_box_set_child_secondary ((GtkButtonBox*) bbox, (GtkWidget*) save_button, TRUE);
#line 372 "snapz.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) bbox, FALSE, FALSE, (guint) 0);
#line 374 "snapz.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
#line 375 "snapz.vala"
	gtk_widget_show_all ((GtkWidget*) vbox);
#line 377 "snapz.vala"
	g_signal_connect ((GtkObject*) self, "destroy", (GCallback) _gtk_main_quit_gtk_object_destroy, NULL);
#line 1345 "snapz.c"
	_g_object_unref0 (vbox);
	_g_object_unref0 (bbox);
	_g_object_unref0 (crop_button);
	_g_object_unref0 (highlight_button);
	_g_object_unref0 (imgur_button);
	_g_object_unref0 (save_button);
	return self;
}


#line 328 "snapz.vala"
SnapzWin* snapz_win_new (GdkPixbuf* shot) {
#line 328 "snapz.vala"
	return snapz_win_construct (TYPE_SNAPZ_WIN, shot);
#line 1360 "snapz.c"
}


#line 380 "snapz.vala"
static void snapz_win_save (SnapzWin* self) {
#line 1366 "snapz.c"
	GError * _inner_error_;
	GtkFileChooserDialog* dialog;
	gint response;
#line 380 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 1372 "snapz.c"
	_inner_error_ = NULL;
#line 381 "snapz.vala"
	dialog = g_object_ref_sink ((GtkFileChooserDialog*) gtk_file_chooser_dialog_new (NULL, (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_SAVE, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_OK, GTK_RESPONSE_OK, NULL, NULL));
#line 386 "snapz.vala"
	gtk_file_chooser_set_current_name ((GtkFileChooser*) dialog, "Screenshot.png");
#line 387 "snapz.vala"
	response = gtk_dialog_run ((GtkDialog*) dialog);
#line 388 "snapz.vala"
	if (response == GTK_RESPONSE_OK) {
#line 1382 "snapz.c"
		{
			char* _tmp0_;
#line 390 "snapz.vala"
			shot_canvas_save (self->priv->canvas, _tmp0_ = gtk_file_chooser_get_filename ((GtkFileChooser*) dialog), &_inner_error_);
#line 1387 "snapz.c"
			_g_free0 (_tmp0_);
			if (_inner_error_ != NULL) {
				goto __catch1_g_error;
			}
		}
		goto __finally1;
		__catch1_g_error:
		{
			GError * e;
			e = _inner_error_;
			_inner_error_ = NULL;
			{
				_g_error_free0 (e);
			}
		}
		__finally1:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (dialog);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
#line 395 "snapz.vala"
	gtk_object_destroy ((GtkObject*) dialog);
#line 1413 "snapz.c"
	_g_object_unref0 (dialog);
}


#line 435 "snapz.vala"
static void _lambda8_ (Block1Data* _data1_) {
#line 1420 "snapz.c"
	SnapzWin * self;
	self = _data1_->self;
#line 436 "snapz.vala"
	gtk_object_destroy ((GtkObject*) _data1_->dlg);
#line 1425 "snapz.c"
}


#line 435 "snapz.vala"
static void __lambda8__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 1431 "snapz.c"
	_lambda8_ (self);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	++_data1_->_ref_count_;
	return _data1_;
}


static void block1_data_unref (Block1Data* _data1_) {
	if ((--_data1_->_ref_count_) == 0) {
		_g_object_unref0 (_data1_->self);
		_g_object_unref0 (_data1_->dlg);
		g_slice_free (Block1Data, _data1_);
	}
}


#line 447 "snapz.vala"
static void _lambda9_ (Block2Data* _data2_) {
#line 1453 "snapz.c"
	SnapzWin * self;
	self = _data2_->self;
#line 448 "snapz.vala"
	gtk_object_destroy ((GtkObject*) _data2_->dlg);
#line 1458 "snapz.c"
}


#line 447 "snapz.vala"
static void __lambda9__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 1464 "snapz.c"
	_lambda9_ (self);
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
	++_data2_->_ref_count_;
	return _data2_;
}


static void block2_data_unref (Block2Data* _data2_) {
	if ((--_data2_->_ref_count_) == 0) {
		_g_object_unref0 (_data2_->self);
		_g_object_unref0 (_data2_->dlg);
		g_slice_free (Block2Data, _data2_);
	}
}


#line 398 "snapz.vala"
static void snapz_win_imgur_upload (SnapzWin* self) {
#line 1486 "snapz.c"
	GError * _inner_error_;
	guint8* _tmp0_;
	gint _content_size_;
	gint content_length1;
	guint8* content;
	char* path;
	SoupSessionSync* session;
	char* _tmp1_;
	SoupMessage* _tmp2_;
	SoupMessage* message;
#line 398 "snapz.vala"
	g_return_if_fail (self != NULL);
#line 1499 "snapz.c"
	_inner_error_ = NULL;
	content = (_tmp0_ = NULL, content_length1 = 0, _content_size_ = content_length1, _tmp0_);
#line 403 "snapz.vala"
	path = g_strdup ("/tmp/imgur-upload.png");
#line 1504 "snapz.c"
	{
#line 405 "snapz.vala"
		shot_canvas_save (self->priv->canvas, path, &_inner_error_);
#line 1508 "snapz.c"
		if (_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
#line 406 "snapz.vala"
		read_file (path, &content, &content_length1);
#line 1514 "snapz.c"
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			{
#line 411 "snapz.vala"
				g_unlink (path);
#line 1526 "snapz.c"
			}
			_g_error_free0 (e);
			content = (g_free (content), NULL);
			_g_free0 (path);
#line 409 "snapz.vala"
			return;
#line 1533 "snapz.c"
		}
	}
	__finally2:
	{
#line 411 "snapz.vala"
		g_unlink (path);
#line 1540 "snapz.c"
	}
	if (_inner_error_ != NULL) {
		content = (g_free (content), NULL);
		_g_free0 (path);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
#line 414 "snapz.vala"
	session = (SoupSessionSync*) soup_session_sync_new ();
#line 415 "snapz.vala"
	message = (_tmp2_ = _g_object_ref0 (soup_form_request_new ("POST", "http://imgur.com/api/upload.json", "key", "83b56669cd32cbd97fd604ecc8418037", "image", _tmp1_ = g_base64_encode (content, content_length1), NULL, NULL)), _g_free0 (_tmp1_), _tmp2_);
#line 1553 "snapz.c"
	{
		Block1Data* _data1_;
		guint status;
		char* response;
		char* url;
		_data1_ = g_slice_new0 (Block1Data);
		_data1_->_ref_count_ = 1;
		_data1_->self = g_object_ref (self);
#line 423 "snapz.vala"
		status = soup_session_send_message ((SoupSession*) session, message);
#line 424 "snapz.vala"
		if (status != 200) {
#line 1566 "snapz.c"
			char* _tmp4_;
			char* _tmp3_;
			GError* _tmp5_;
			_inner_error_ = (_tmp5_ = g_error_new_literal (IMGUR_ERROR, IMGUR_ERROR_FAIL, _tmp4_ = g_strconcat ("HTTP status ", _tmp3_ = g_strdup_printf ("%u", status), NULL)), _g_free0 (_tmp4_), _g_free0 (_tmp3_), _tmp5_);
			{
				block1_data_unref (_data1_);
				if (_inner_error_->domain == IMGUR_ERROR) {
					goto __catch3_imgur_error;
				}
				block1_data_unref (_data1_);
				content = (g_free (content), NULL);
				_g_free0 (path);
				_g_object_unref0 (session);
				_g_object_unref0 (message);
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
#line 426 "snapz.vala"
		response = g_strdup (soup_message_body_flatten (message->response_body)->data);
#line 427 "snapz.vala"
		url = imgur_parse_response (response, &_inner_error_);
#line 1590 "snapz.c"
		if (_inner_error_ != NULL) {
			_g_free0 (response);
			block1_data_unref (_data1_);
			if (_inner_error_->domain == IMGUR_ERROR) {
				goto __catch3_imgur_error;
			}
			_g_free0 (response);
			block1_data_unref (_data1_);
			content = (g_free (content), NULL);
			_g_free0 (path);
			_g_object_unref0 (session);
			_g_object_unref0 (message);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_data1_->dlg = g_object_ref_sink ((GtkMessageDialog*) gtk_message_dialog_new_with_markup ((GtkWindow*) self, GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_INFO, GTK_BUTTONS_OK, "<tt>%s</tt>", url, NULL));
#line 434 "snapz.vala"
		gtk_window_set_title ((GtkWindow*) _data1_->dlg, "Upload Success");
#line 435 "snapz.vala"
		g_signal_connect_data ((GtkDialog*) _data1_->dlg, "response", (GCallback) __lambda8__gtk_dialog_response, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 438 "snapz.vala"
		gtk_dialog_run ((GtkDialog*) _data1_->dlg);
#line 1614 "snapz.c"
		_g_free0 (response);
		_g_free0 (url);
		block1_data_unref (_data1_);
	}
	goto __finally3;
	__catch3_imgur_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			Block2Data* _data2_;
			_data2_ = g_slice_new0 (Block2Data);
			_data2_->_ref_count_ = 1;
			_data2_->self = g_object_ref (self);
			_data2_->dlg = g_object_ref_sink ((GtkMessageDialog*) gtk_message_dialog_new ((GtkWindow*) self, GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, "%s", e->message));
#line 446 "snapz.vala"
			gtk_window_set_title ((GtkWindow*) _data2_->dlg, "Upload Error");
#line 447 "snapz.vala"
			g_signal_connect_data ((GtkDialog*) _data2_->dlg, "response", (GCallback) __lambda9__gtk_dialog_response, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 450 "snapz.vala"
			gtk_dialog_run ((GtkDialog*) _data2_->dlg);
#line 1637 "snapz.c"
			_g_error_free0 (e);
			block2_data_unref (_data2_);
		}
	}
	__finally3:
	if (_inner_error_ != NULL) {
		content = (g_free (content), NULL);
		_g_free0 (path);
		_g_object_unref0 (session);
		_g_object_unref0 (message);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	content = (g_free (content), NULL);
	_g_free0 (path);
	_g_object_unref0 (session);
	_g_object_unref0 (message);
}


static void snapz_win_class_init (SnapzWinClass * klass) {
	snapz_win_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SnapzWinPrivate));
	G_OBJECT_CLASS (klass)->finalize = snapz_win_finalize;
}


static void snapz_win_instance_init (SnapzWin * self) {
	self->priv = SNAPZ_WIN_GET_PRIVATE (self);
}


static void snapz_win_finalize (GObject* obj) {
	SnapzWin * self;
	self = SNAPZ_WIN (obj);
	_g_object_unref0 (self->priv->canvas);
	self->priv->selection_buttons = (_vala_array_free (self->priv->selection_buttons, self->priv->selection_buttons_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (snapz_win_parent_class)->finalize (obj);
}


GType snapz_win_get_type (void) {
	static volatile gsize snapz_win_type_id__volatile = 0;
	if (g_once_init_enter (&snapz_win_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SnapzWinClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) snapz_win_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SnapzWin), 0, (GInstanceInitFunc) snapz_win_instance_init, NULL };
		GType snapz_win_type_id;
		snapz_win_type_id = g_type_register_static (GTK_TYPE_WINDOW, "SnapzWin", &g_define_type_info, 0);
		g_once_init_leave (&snapz_win_type_id__volatile, snapz_win_type_id);
	}
	return snapz_win_type_id__volatile;
}


#line 462 "snapz.vala"
GdkPixbuf* screenshot (void) {
#line 1694 "snapz.c"
	GdkPixbuf* result = NULL;
	GdkScreen* screen;
#line 463 "snapz.vala"
	screen = _g_object_ref0 (gdk_screen_get_default ());
#line 1699 "snapz.c"
	result = _g_object_ref0 (gdk_pixbuf_get_from_drawable (NULL, (GdkDrawable*) gdk_screen_get_root_window (screen), NULL, 0, 0, 0, 0, gdk_screen_get_width (screen), gdk_screen_get_height (screen)));
	_g_object_unref0 (screen);
#line 464 "snapz.vala"
	return result;
#line 1704 "snapz.c"
}


#line 469 "snapz.vala"
gint _vala_main (char** args, int args_length1) {
#line 1710 "snapz.c"
	gint result = 0;
	GdkPixbuf* shot;
	SnapzWin* win;
#line 470 "snapz.vala"
	gtk_init (&args_length1, &args);
#line 472 "snapz.vala"
	shot = screenshot ();
#line 473 "snapz.vala"
	win = g_object_ref_sink (snapz_win_new (shot));
#line 474 "snapz.vala"
	gtk_widget_show ((GtkWidget*) win);
#line 475 "snapz.vala"
	gtk_main ();
#line 1724 "snapz.c"
	result = 0;
	_g_object_unref0 (shot);
	_g_object_unref0 (win);
#line 477 "snapz.vala"
	return result;
#line 1730 "snapz.c"
}


#line 469 "snapz.vala"
int main (int argc, char ** argv) {
#line 469 "snapz.vala"
	g_type_init ();
#line 469 "snapz.vala"
	return _vala_main (argv, argc);
#line 1740 "snapz.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




